# Generated by Django 3.2.10 on 2022-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=5000, null=True)),
                ('topic', models.CharField(choices=[('Bullying', 'Bullying'), ('Mental Illness', 'Mental Illness'), ('Stress', 'Stress'), ('Disability', 'Disability'), ('Despression', 'Despression')], default='Bullying', max_length=50, null=True)),
            ],
        ),
    ]
