# Generated by Django 3.2.10 on 2022-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportcard_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcard',
            name='answer',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
